version: '2.4'

volumes:
  db:

services:
  app:
    build: .
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 8000:8000

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080
